repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: detect-private-key

  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.5.0
    hooks:
      - id: detect-secrets
        # Generate this file locally with: `uvx detect-secrets scan > .secrets.baseline`
        args: ["--baseline", ".secrets.baseline"]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.5
    hooks:
      - id: ruff
        args: ["--fix", "--exit-non-zero-on-fix"]
      - id: ruff-format

  # Optional: enable Black if you prefer it over ruff-format.
  # - repo: https://github.com/psf/black
  #   rev: 24.8.0
  #   hooks:
  #     - id: black

